## 错误边界

### 本文速览：

- 错误边界



------



### 错误边界（Error boundaries）

> React 16+ 提供了 Error Boundaries 错误边界。 
>
> 目的：【某些UI崩溃，不至于整个webapp崩溃】。**官方** ：部分 UI 中的 JavaScript 错误不应该破坏整个应用程序。 为了解决 React 用户的这个问题，React 16引入了一个 “错误边界(Error Boundaries)” 的新概念。
>
> **必须是class组件** 

**错误边界是 React 组件**，它可以 **在子组件树的任何位置捕获 JavaScript 错误，记录这些错误，并显示一个备用 UI** ，而不是使整个组件树崩溃。



>  错误边界(Error Boundaries) 在渲染，生命周期方法以及整个组件树下的构造函数中捕获错误。



### 注意

错误边界**无法**捕获以下场景中产生的错误：

- 事件处理（[了解更多](https://zh-hans.reactjs.org/docs/error-boundaries.html#how-about-event-handlers)）
- 异步代码（例如 `setTimeout` 或 `requestAnimationFrame` 回调函数）
- 服务端渲染
- 它自身抛出来的错误（并非它的子组件）





### 1. 编写错误边界组件

> 必须是class组件。如下

~~~js
// ErrorBoundary.jsx
import React, { Component } from 'react';

class ErrorBoundary extends Component {
    constructor(props) {
        super(props);
        this.state = {
            hasError: false
        };
    }

    static getDerivedStateFromError() {
        // 更新 state 使下一次渲染能够显示降级后的 UI
        return { hasError: true };
    }

    componentDidCatch(error, errorInfo) {
        // 你同样可以将错误日志上报给服务器
        console.group();
        console.log('ErrorBoundary catch a error:');
        console.info('error', error);
        console.info('error info', errorInfo);
        console.groupEnd()
    }


    render() {
        console.log('component ErrorBoundary render...');
        const { children } = this.props;
        const { hasError } = this.state;
        return (
            <>
                {
                    hasError ? 'Something Wrong' : children
                }
            </>

        )
    }
}

export default ErrorBoundary;
~~~



~~~js
// ErrorComponent.tsx
import React, { Component } from 'react';

class ErrorComponent extends Component{
    constructor(props) {
        super(props);
        this.state = {
            counter: 0
        }
        this.handleClick = this.handleClick.bind(this);
    }

    handleClick() {
        // 事件处理的错误，ErrorBoundary无法捕捉
        // if (this.state.counter === 5) {
        //     throw new Error();
        // }
        this.setState({
            counter: this.state.counter + 1
        });

    }

    render() {
        console.log('component ErrorComponent render...');
        const { counter } = this.state;
        const { handleClick } = this;
        if (counter === 5) {
            throw new Error('counter creashed!');
        }
        return (
            <>
                <p>this component will throw Error when the counter equal to 5</p>
                <p>counter : {counter}</p>
                <button onClick={handleClick}>add</button>
            </>
        )
    }
}

export default ErrorComponent;
~~~



**组合**

~~~js
// App.jsx
import React from 'react';

import ErrorBoundary from './ErrorBoundary';
import ErrorComponent from './ErrorComponent';

function App() {
  return (
    <div className="App">
        <ErrorBoundary>
          <ErrorComponent />
        </ErrorBoundary>
    </div>
  );
}

export default App;
~~~

![image.png](https://i.loli.net/2021/08/15/T7wXlzJ8PBKuFvc.png)





### 打包静态资源

> 不再devserver测试的原因是，在cra的配置中，webpack会捕捉Error并显示错误蒙版，不便于看到测试结果

在package.json添加字段`"homepage": "."`



